server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testDb
    username: sadik
    password: "sadik"
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_test.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "test"

build:
  version: "3.0"

cards:
  message: "Welcome to BS23 Bank cards related local APIs"
  contactDetails:
    name: "Sadik - Developer"
    email: "sadik@bs23.com"
  onCallSupport:
      - (412) 419-3491
      - (915) 382-1932