services:
  accounts:
    image: "sadikbs23/accounts:latest"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bs23-bank

  cards:
    image: "sadikbs23/cards:latest"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bs23-bank
  loans:
    image: "sadikbs23/loans:latest"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bs23-bank
networks:
  bs23-bank:
    driver: "bridge"