build:
  version: "3.0"

accounts:
  message: "Welcome to BS23 Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bs23.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345