build:
  version: "1.0"

cards:
  message: "Welcome to BS23 Bank cards related prod APIs "
  contactDetails:
    name: "Sabuj - Product Owner"
    email: "sabuj@bs23.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721