build:
  version: "3.0"

cards:
  message: "Welcome to BS23 Bank cards related local APIs"
  contactDetails:
    name: "Sadik - Developer"
    email: "sadik@bs23.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932