build:
  version: "3.0"

loans:
  message: "Welcome to BS23 Bank loans related local APIs "
  contactDetails:
    name: "Sadik - Developer"
    email: "sadik@bs23.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934